Flicker.xcodeproj/project.pbxproj
Flicker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Flicker/Flicker.entitlements
Flicker/Global/Supports/AppDelegate.swift
Flicker/Models/Message/ImageMediaItem.swift
Flicker/Models/Message/Message.swift
Flicker/Models/Message/Sender.swift
Flicker/Screens/Login/KeychainItem.swift
Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/Main/MainViewController.swift
Flicker/Screens/Message/Cell/MessageTableViewCell.swift
Flicker/Screens/Message/MessageViewController.swift
Flicker/Screens/MessageRoom/MessageRoomViewController.swift
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/Tabbar/TabbarViewController.swift

- 애플아이디를 사용한 로그인을 앱의 주 로그인으로 사용하기 위해 기초적인 로그인을 구현했습니다.
- 코비가 MessageKit을 삭제 후 나중에 추가하신다고 하셔서 관련 부분 모두 주석처리 및 패키지를 삭제진행하였습니다.
- 다른 분들이 작업 전에 루키가 작업한 코드와 이번 PR을 합한 후 시작하기 위함입니다.
- KeyChainItem값을 통해 로그인여부를 파악하는 로직입니다.
- 파이어베이스와 연동을 위해 파이어베이스에서 애플 로그인을 연동한 부분을 찾아 수정해야하며, 이미 로그인 한 사람일 경우 바로 홈 화면으로 넘어가도록 로직을 좀 더 수정해야합니다.
</p>
- 로그인 버튼을 누르면 애플로그인이 되고 원래는 설정에 있는 SignOut버튼을 누르면 저장된 키체인 값이 삭제되며 다시 로그인을 해야하지만 추가작업이 필요합니다.
- #3
- https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple

✨애플 로그인 기초 구현 및 MessageKit을 삭제 후 이슈들을 해결했습니다.

---

.gitattributes

Xcode 파일을 분해해서 보면 pbxproj파일과 workspace파일이 있습니다.
한마디로 한개의 프로젝트가 아닌 여러개의 프로젝트를 한군데 모아 작업하고 싶으면 workspace를 만들어서 관리해야합니다. 예를 들어cocoapods 등을 사용하여 외부 라이브러리 등을 내 프로젝트에 추가한 경우에 xcworkspace에서 내 프로젝트와 외부 라이브러리를 연결해주는 연할을 하게됩니다. (외부 라이브러리 추가가 없는 경우 pbxproj 파일만 있습니다.)
프로젝트 내부에서 생성된 파일들을 파일 유형에 따라 reference를 저장하고 있습니다. 이 project.pbxproj는 사실 git을 사용할 경우 충돌이 일어나는 주요 파일 중 하나입니다. 
2명의 팀원이 작업을 위해 각자 A 파일, B 파일을 생성하여 각자 커밋한 경우 한 쪽에는 B 파일의 reference, 다른 쪽은 A 파일의 reference가 없습니다. 그래서 두 작업에서 사용된 project.pbxproj 파일은 서로 다른 reference를 가지고 있어서 conflict가 일어납니다. 그리고 이 충돌이 고치기 쉽지 않은 것이 project.pbxproj가 깨지면 프로젝트 자체가 열리지 않습니다. 그러므로 이럴 때는 에디터나 소스트리 같은 형상 관리 툴로 해당 충돌을 수정해야 합니다. (아마 많이들 겪으셨을거라고 생각합니다,,,)
Git은 우리가 머지 할 때 텍스트 파일을 비교해서 수정사항의 충돌여부를 판별하게 됩니다. 하지만 pbxfile은 워낙에 알아들을 수 없는 텍스트로 구성되어있어 개발자들이 건드리기가 쉽지않습니다. 
그래서 이런 …

Merge시 pbxfile 충돌방지를 위해 gitattribute를 추가합니다.

---

Flicker.xcodeproj/project.pbxproj
Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
Flicker/Screens/Main/Cell/RegionCollectionViewCell.swift
Flicker/Screens/Main/MainViewController.swift
Flicker/Screens/Main/UIComponent/RegionListHorizontalView.swift
Flicker/Screens/Tabbar/TabbarViewController.swift

- 메인 화면을 구현하였습니다.
- 데이터를 불러오는 코드 없이, 간단한 UI만 구성하였습니다.
- 지역 태그를 선택했을 때, 어떤 태그를 클릭했는지 정도까지만 코드를 구현하였습니다.
</p>
- 해당 브랜치에서 빌드하시면 됩니다. 
- 작가 썸네일에서, 사진 배경에 따라, 글자 스타일이 변경되거나 다른 디자인을 해야할 것 같습니다.
- 배경이 밝으면, 기존의 하얀색 폰트가 잘 보이지 않습니다.
- 마찬가지로, 작가 썸네일 안의, 작가 프로필이미지도 인스타그램처럼 테두리라도 넣을까 싶습니다.
- #16

💄 MainView UI 구현

---

Flicker/Screens/SignUp/LoginProfileViewController.swift

- 처음 UI 작업 시 닉네임을 적는 textField를 피그마 디자인과 다르게 작업한 점이 있어 이를 수정 했습니다.
- 이미지 셀렉뷰도 또한 피그마와 동일시하게 만들었습니다만, 이미지뷰 컴포넌트자체에 백그라운드 색과 이미지를 동시에 넣는 것이 막상 생각나지않아서, 새로 카메라 이미지 뷰를 생성하여 오토레이아웃을 통해 내부에 있도록 하였습니다.
- 닉네임을 적는 텍스트 필드 또한 새로 만들기보다 기존에 있던 컴포넌트의 오토레이아웃 값을 수정하고 x버튼 및 divider를 추가하여 작업했습니다.
- x버튼을 누르면 textField에 text값이 사라짐과 동시에 원래 placeholder 값인 닉네임을 입력해 주세요! 가 뜨는데 placeHolder가 처음에만 적용되어 있고 그 뒤로 x를 누를 경우 안뜨게 하는 것이 맞을지? 의문입니다.
</p>
- 빌드 후 로그인 flow(회원가입)을 따라가면 됩니다!
closed #34

💄 LoginProfileViewController를 피그마에 맞게 수정했습니다.

---

Flicker/Screens/Login/LoginViewController.swift

- 로그인 화면이 로드될 때 바로 EmailTextField로 가도록 되어있어 키보드가 뜨는 현상이 있어 이는 UX적으로 맞지 않다고 생각해 이를 제거하는 작업이 필요했습니다.
- 처음 테스크는 로그인시 이메일에 대한 유효성 검사를 하는 것 이였습니다. 하지만 이 화면은 회원가입 화면이 아닌, 로그인을 화는 화면이라 제 판단에는 유효성 검사가 아닌 입력을 한번 더 확인하라는 얼럿이 더 UX에 맞다고 생각이 들어 테스크와는 다르게 구현을 했습니다.
- 이 뷰에는 오히려 비밀번호 찾기 기능이 추가되어야 한다고 생각이 듭니다..
- 뷰가 로드되자마자 이메일 텍스트 필드로 클릭이 가는 코드를 제거했습니다.
- 이메일 텍스트필드, 패스워드 텍스트 필드가 비어 있거나, 로그인에 실패 했을때 얼럿을 통해 확인을 시켜주는 기능을 구현했습니다.
<p align="center">
</p>
- 현재 작성 중인 Pull Request와 관련된 PR과 Issues가 있다면 나열합니다.
- closed #41 

:sparkles: 로그인 실패 시 얼럿을 통한 확인 및 뷰가 로드 될 때 키보드가 뜨는 이슈 제거했습니다.

---

Flicker/Screens/Profile/ProfileHeaderVIew.swift
Flicker/Screens/Profile/ProfileViewController.swift

추가로 필요없는 코드를 삭제하여 조금 더 클-린 해졌습니다.
- 하디의 요청으로 기능을 테스트하기 위하여 네비게이션을 붙였습니다. 진작에 신경 썼어야 했는데 귀찮게 해서 죄송합니다!
- 기존에 급하게 만들다보니 겹치는 코드가 있는데 인식하지 못 하고 있던걸 인식하여 지웠습니다.
- 프로필 화면에서 카드를 탭하면 네비게이션으로 프로필을 수정하거나 탈퇴 혹은 로그인 할 수 있는 화면으로 이동합니다. 여기에 인자값을 주어 화면 변경되는 것을 생각해보았으나 로그인 화면 구성을 어떻게 하는지 잘 몰라 일단은 그냥 PR 올립니다!
- 프로필 화면에서 카드를 탭하시면 됩니다.

CardView에 네비게이션 기능을 넣었습니다

---

Flicker.xcodeproj/project.pbxproj
Flicker/Global/Base/BaseViewController.swift
Flicker/Global/Supports/SceneDelegate 2.swift
Flicker/Global/Supports/SceneDelegate.swift
Flicker/Global/Utils/AppleLoginManager.swift
Flicker/Global/Utils/FirebaseManager.swift
Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/ProfileSetting/InputPassword/InputPasswordViewController.swift
Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift
Flicker/Screens/SignUp/LoginProfileViewController.swift
Flicker/Screens/SignUp/SignUpViewController.swift
Flicker/Screens/Tabbar/TabbarViewController.swift
Flicker/Screens/WithDraw/WithDrawViewController.swift
Flicker/Screens/WithDraw/WithDrawViewController.swift~refs/remotes/origin/Feat/38-SignOutView

- 회원가입 및 로그인, 로그아웃 과정에 필요한 기능 및 버그들을 수정 및 추가 했습니다.
현재 뷰들끼리 데이터를 넘길 때 이전 화면에서 입력이 끝난 데이터에 대해서 값을 넘기게 되어 직접 넘기는 식으로 구현을 했습니다.
다만 로그인에 대한 재인증 시 이메일인증과 애플로그인 인증에 대한 분기처리를 추가해야하며,
애플 로그인 인증은 맨 처음 LoginVC에서 생성된 난수값 nonce와 idToken값을 그대로 가져와서 로그인을 한 사람이면
그냥 넘어가도록 우선은 구현 했는데 이렇게 짜는건 제 생각엔 아닌 것  같다고 생각이 듭니다. 이때 재인증이 아닌 애플 로그인은 재 로그인식으로 해도 괜찮지 않을까 싶은 생각입니다.
우선 appleLoginManager에 로그인 관련 함수들을 모아놓고 shared를 통해 싱글톤으로 다 관리할 수 있도록 코드르 바꿔볼 예정입니다. 
</p>
- InputPasswordViewController에 있는 didTapSignInButton내부에 reAuthUser()메소드를 사용하시면 이메일 재인증 처리가 되며 이는 비밀번호를 입력하고 비밀번호가 일치해야 넘어갑니다.
- appleLoginReAuthUser()메소드를 사용하시면 애플로그인 재인증으로 되어 비밀번호 입력 없이 그냥 넘어갑니다. 
- closed #37 
- closed #38 
- closed #42 
- closed #43
- …

🎨💄✨🐛 로그인, 로그아웃 플로우를 조져놨습니다.

---

Flicker/Global/Supports/Info.plist

- 다크모드에 대한 색이 정해지지 않고 현재 다크모드를 고려하여 색을 지정하는 것에 대한 테스크보다 다른 부분이 크다고 생각합니다.
그래서 위와 같은 이유로 우선은 사용자의 휴대폰이 다크모드여도 앱의 모드는 라이트모드로 고정시켰습니다.
- info.plist에 모드를 라이트모드로 고정시켰습니다.
- 
<p align="center">
</p>
- 현재 작성 중인 Pull Request와 관련된 PR과 Issues가 있다면 나열합니다.
- closed #56 

:lipstick: 다크모드를 미지원으로 고정합니다.

---

Flicker.xcodeproj/project.pbxproj
Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/Login/New Group/PopUpViewController.swift
Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/ProfileSetting/InputPassword/InputPasswordViewController.swift

- 둘러보기 기능을 삭제하며, 그 빈공간에 무엇을 채워야 하나 고민을 했습니다.
- 생각해보니 비밀번호 찾기 기능자체가 없으면 앱스토어에서 통과가 어려울 것이라는 저의 생각으로 파이어베이스 로그인에 비밀번호 재설정기능을 추가하게 되었습니다.
- 뒷 배경이 불투명한 VC로 팝업처럼 보이는 뷰를 추가하여 이메일을 입력하도록 작업했습니다.
- 이메일을 입력하고 올바른 이메일일 경우 메일이 보내지며, 입력한 이메일에서 비밀번호 재설정을 할 수 있는 링크를 받습니다.
- 이 후 링크를 통해 재설정한 비밀번호로 다시 이용이 가능합니다.
- 화면녹화 동영상입니다 죄송함둥
- 로그인 관련 작업을 하면서 얼럿이 뜨는데 화면이 넘어가는 버그를 바로 해결했습니다.
</p>
https://user-images.githubusercontent.com/81131715/202655957-1d29bf47-6574-4385-92c8-4900f70e41ff.mov
- Cmd + R
- closed #63 
- https://firebase.google.com/docs/auth/ios/manage-users

✨ 비밀번호 재설정 기능 추가했습니다.

---

Flicker/Network/NetworkManager.swift
Flicker/Screens/Artist/ArtistTappedViewController.swift
Flicker/Screens/Artist/ImageViewController.swift

UI 작업들을 머지 후 버그 테스트하면서 발견했던 사항들을 수정합니다.
헤더뷰의 사이즈를 reset하는 함수를 reloadData가 확실하게 끝난 후 실행되도록 조정하였습니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/blob/82492d5ac1e6629dce11644905029023474d79fb/Flicker/Screens/Artist/ArtistTappedViewController.swift#L132-L134
reloadData가 끝나야 그려진 헤더뷰의 subview를 기반으로 헤더뷰 사이즈를 재조정할 수 있는데  reloadData 과정 중에 헤더뷰 사이즈가 넘어오지 않은 상태로 뷰를 그리기 때문에 맨 처음 뷰를 그릴 때 헤더뷰가 그려지지 않은 것으로 생각됩니다.
이미지 통신 속도를 최적화하기 위해서 여러 장의 이미지를 병렬적으로 (동시에) 통신해서 가져오는 절차를 거치게 됩니다. 
( 캐시에서 이미지를 찾아서 가져오는 과정이 동시에, 비동기적으로 이루어지기 때문에 ABC, BAC, CBA 등으로 순서가 무작위로 들어오게 되는 것으로 추정합니다.)
https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/blob/82492d5ac1e6629dce11644905029023474d79fb/Flicker/Network/NetworkManager.swift#L49-L60
결과적으로 원래는 withThrowingTaskGroup 이라는 함수를 써서 하나의 Task 안에 여러 …

🐛 ArtistTappedView UI 및 이미지 로드 관련 버그를 수정했습니다.

---

Flicker/Global/Extensions/UIViewController+Extension.swift
Flicker/Screens/Profile/ProfileViewController.swift

- Profile에서 UI 관련 버그를 일으키는 요인인 Navigationbar를 지우고 효율성을 향상시키는 조치를 취했습니다.
기존 UI에서는 다른 화면으로 이동하여 View가 사라지고 다시 등장하게 되면 전체적인 레이아웃이 굉장히 따로 노는것을 볼 수 있었습니다.
해당 뷰를 떠나고 다시 들어올 때 navigation을 이용하여 들어오게 됩니다. 이 때, 화면에 navigationbar가 등장하여 화면을 가리게 되고 SafeArea와 상호작용으로 전체적인 비율이 어긋나 문제가 일어나는 것으로 보입니다. 이에 화면이 그려질 때마다 네비게이션바를 hidden 처리하여 지우게 되었습니다.
---
네비게이션 관련 코드의 중복선언으로 중복코드가 점점 증가하는 것을 발견하고 현재 상황에서 도움이 되는 방법을 생각해봤습니다.
UIViewController+Extension에 제네릭 타입을 이용하여 두가지 함수를 작성했습니다.
- transition 함수
- changeRootView 함수
1. transition<T: UIViewController>(_ viewController: T, transitionStyle: TransitionStyle = .present)
transition 함수의 경우에는 총 네가지의 navigation 관련 기능 수행이 가능한 함수로 매개변수로 이동하고자 하는 View와 아래 네가지 방식을 구현하고자 하는 방법에 따라 입력하면 됩니다.
- .present
- .presentNavigation
- .presentFullNavigation
- .push
2. func …

프로필뷰에서 네비게이션 바를 지우고 ViewControllerExtension에 네비게이션 관련 함수를 넣었습니다. [#66]

---

Flicker.xcodeproj/project.pbxproj
Flicker/Global/Base/BaseViewController.swift
Flicker/Global/Utils/EmailViewController.swift
Flicker/Screens/Profile/ProfileViewController.swift

- 신고하기 기능이 다양한 곳에서 쓰임에 따라 개발의 필요가 있었습니다.
- 현재 이메일 발송 기능의 경우 ProfileViewController에만 존재했습니다.
- 이를 BaseViewController로 이동시켜 상속 받는 모든 ViewController에서 해당 기능을 이용할 수 있도록 했습니다.
sendReportMail(userName: "현재 로그인된 유저의 닉네임", reportType: .askSomething)
위와 같은 형식으로 함수를 이용합니다.
현재 리포트하는 양식으로 세가지가 있습니다.
- .askSomething
사용자가 서비스에 대해 문의할 수 있는 양식이 있습니다.
- .reportAnotherUser
사용자가 게시글 기반으로 사용자를 신고할 수 있는 양식이 있습니다.
- .reportChatUser
사용자가 채팅 진행중인 상대방을 신고할 수 있는 양식이 있습니다.
- BaseViewController를 상속하는 ViewController에서 위에 언급한 함수를 호출해서 확인하시면 됩니다.

✨BaseViewController로 이메일 발송 기능 이관 및 신고 양식 개발

---

Flicker/Models/User.swift
Flicker/Screens/Profile/ProfileViewController.swift

- UserDefault에 값을 저장만 하고 로그아웃하거나 회원탈퇴 할때 삭제하는 기능이 없어 로그아웃 후 앱을 들어가도 메인 뷰에서 지역이 전에 설정했던 데로 그대로 남아있어 이를 삭제하는 코드를 추가했습니다.
- UserDefault 저장된 값을 삭제하는 코드를 추가했습니다.
- 로그아웃 혹은 회원탈퇴 후 메인화면에서 지역태그 값이 초기화가 되어있음을 확인하면 됩니다.
- closed #104

✨ UserDefault에 있는 값을 회원가입 및 로그아웃 할때 삭제하는 코드를 추가했습니다.

---

Flicker/Global/Utils/FirebaseManager.swift
Flicker/Screens/SignUp/SignUpViewController.swift

- 이메일이 서버에 있으면 회원가입할때 유저데이터가 생성되지 않지만 화면은 넘어가는 버그가 존재했습니다.
- 이를 해결하기 위해 서버에서 이메일 존재여부를 체크하여 이메일이 중복되면 넘어갈 수 없도록 UX를 수정해야했습니다.
- 유저가 입력한 이메일 값을 서버와의 통신을 통해 값을 리턴받는 식으로 함수를 만들었습니다.
- 리턴받을때 이미 있는 이메일이면 쿼리의 주소값을 배열로 받으며 존재하지 않는 이메일은 빈 배열을 리턴받습니다.
- 이를 이용하여 받는 값에 대해 isEmpty를 활용하여 함수의 리턴값을 boolean형식으로 하여 분기처리를 했습니다.
</p>
- 파이어베이스 서버내의 이미 있는 이메일로 로그인 하는 경우 화면이 넘어갈 수 없도록 구현했습니다.
- closed #106 
- https://firebase.google.com/docs/firestore/query-data/queries#swift
- PR #110

✨ 🐛 서버에 중복된 이메일이여도 로그인처리되는 것 처럼 보이는 버그를 해결했습니다.

---

Flicker/Models/User.swift
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift

유저가 현재 프로필 세팅뷰를 이용 못 하고 있어 해당 기능을 개발했습니다.
- 유저는 이제 프로필세팅화면으로 넘어가면 그곳에서 자신의 프로필 이미지와 닉네임을 볼 수 있습니다.
- 수정이 가능하고 이는 파이어베이스 서버에 업로드 되며 유저 디폴츠로 추후 이용하기 편하게 저장됩니다.
- 이 시점에서는 회원가입 뷰에서 필요했던 아티스트로 활동할것인지에 대해 확인할 필요가 없습니다. 관련 UI 요소를 삭제했습니다.
</p>
- UI는 올린 캡쳐 화면을 보시면 되고 기능은 직접 ProfileViewController에서 헤더 카드를 탭하여 변경해보시면 됩니다.
close #107

✨🐛💄 프로필세팅뷰의 기능을 붙였습니다.

---

Flicker/Global/Extensions/ArrayExtension.swift
Flicker/Screens/Artist/ArtistTappedViewController.swift
Flicker/Screens/Artist/HeaderCollectionReusableView.swift

MainView에서 데이터 로드 작업이 끝나고 이를 넘겨받아 작가 디테일뷰의 정보를 업데이트하는 기능이 필요해졌습니다. 이와 관련된 코드 작업을 수행합니다.
코비와 공통된 부분을 작업하다가 머지 과정에서 이전에 머지했었던 파일하나가 누락되었습니다. 그래서 이전 코드를 복붙해서 작가 디테일뷰는 PR과 비슷한 부분이 많습니다. 바뀐 부분 위주로 코멘트를 달아두었습니다
#113

✨ ArtistTappedView 작가 정보 데이터 업데이트 기능 추가

---

Flicker/Screens/Artist/ArtistTappedViewController.swift
Flicker/Screens/Artist/HeaderCollectionReusableView.swift
Flicker/Screens/Chat/ChatViewController.swift
Flicker/Screens/Main/MainViewController.swift

기존에 아티스트탭뷰를 들어갔다가 나오면, 상단 네비바와 탭바가 깜빡거리거나 생기는것이 예상치 못한 경우가 있어서 수정했습니다.
- 작가 상세뷰에서 문의하기를 눌렀을 때, 채팅방의 탭뷰가 안사라졌었습니다.
- 메인뷰에서 작가상세뷰로 넘어갈 때, 네비바가 깜빡거렸습니다.
- 작가상세뷰에서 메인뷰로 돌아갈 때, 네비바가 가끔씩 생겼습니다.
- 스켈레톤 UI를 넣으려고 무리하다가, 네비바와 탭바가 사라지는 주기를 잘못 골랐던 것 같습니다.
- 기존에 있던 코드를 잠시 주석처리하였습니다.
https://user-images.githubusercontent.com/57849386/203318881-ef76fb2e-96a9-4fae-9cd1-2942ef3c2a37.mp4
- closed #131

🐛 아티스트탭뷰를 왔다갔다 할 때 생기는 오류를 수정

---

Flicker/Global/Supports/AppDelegate.swift

-  가로모드의 사용은 우리의 앱과 맞지 않고 설령 지금 한다고 하더라도 앱 출시를 위해 달리는 상황에서 소요가 크다고 생각해 우선은 세로모드로 고정을 하는 코드를 추가합니다.
- appdelegate에 화면이 안돌아가도록 하는 코드를 추가했습니다.
- 화면회전 키시고 휴대폰 돌리시면 됩니다.
- closed #125

✨ 세로모드로 고정하도록 설정을 했습니다.

---

Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/Main/MainViewController.swift
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/Tabbar/TabbarViewController.swift

- 로그인 과정에서 생기는 버그들을 찾아서 수정을 했습니다.
- 회원가입이 아닌 로그인으로 앱을 들어갔을 경우, 네비게이션 바가 생기는 문제를 해결했습니다. tabbarVC가 willAppear가 될때 navigationBar를 hidden해줬습니다.
- 로그아웃 후 애플로그인을 다시 할때 서버에서 값을 불러와 값이 존재하면 바로 메인뷰로 가도록 설정했습니다.
- 또한 로그아웃 후 애플로그인을 다시 할때 유저디폴트가 삭제됬음에도 다시 저장하지 않아 프로필이 뜨지않던 오류를 수정했습니다.
- closed #133

🐛 🚑 네비게이션 바 관련 버그 & 로그아웃 후 애플로그인 시 프로필입력 창으로 가는 버그 & 로그아웃 후 애플로그인할시 Userdefault에 저장하지 않던 오류 수정

---

Flicker/Global/UIComponent/PresentationController.swift
Flicker/Screens/Main/MainViewController.swift

- iOS 15 미만 버전에서는, 하프 모달을 직접 커스텀해서 만들어야 합니다.
- 하프 모달을 커스텀한 PresentationController을 생성했습니다.
https://user-images.githubusercontent.com/57849386/203344876-3da4f290-1328-4e14-943a-e0b7f7b495d0.mp4
- closed #99
https://stackoverflow.com/questions/42106980/how-to-present-a-viewcontroller-on-half-screen

🐛 iOS 최소 지원버전에 맞게 모달을 커스텀했습니다.

---

Flicker/Screens/Artist/ArtistPortfolioCell.swift
Flicker/Screens/Artist/ArtistTappedViewController.swift
Flicker/Screens/Main/MainViewController.swift

3차 버그테스팅에서 모든 뷰의 네비게이션 연결이 이루어졌습니다. 네비바의 중복 삽입, 의도치않은 숨겨짐 등의 버그가 있어서 하디와 코비가 이를 수정했습니다. 그 과정에서 제가 맡은 ArtistTappedView에서 뒤로가기 버튼 없어짐, 스켈레톤뷰 비활성화 등의 현상이 발생해서 이를 수정했습니다.
-> 메인뷰에서 뷰가 없어질 때도 네비게이션바를 없어지도록 하는 코드가 있었습니다. 이를 제거하여 해결했습니다.
-> 메인뷰와 채팅뷰를 연결하는 과정을 원활히 하기 위해 작가 디테일뷰의 라이프사이클 관련 코드가 일부 수정되었습니다. 스켈레톤뷰를 활성화하는 코드가 주석처리되었는데 이를 다시 viewWillAppear에 추가하여 해결했습니다.
-> 작가 디테일뷰 하단에는 작가가 등록한 이미지들이 콜렉션형태로 들어가는데, 그 이미지의 비율이 깨진다는 피드백이 있었습니다 원래는 ScaleToFill인데 scaleAspectFill 로 고쳐서 수정했습니다.
- AspectFill(비율 유지 O, 화면 꽉 채움 O, 이미지 잘림 O)
- AspectFit(비율 유지 O, 화면 꽉 채움 X, 이미지 잘림 X)
- ScaleToFill(비율 유지 X, 화면 꽉 채움 O, 이미지 잘림 X)
** AspectFit 옵션을 채택하면 이렇게 되버립니다.
#142 
[이미지 contentMode 관련 정리](https://sujinnaljin.medium.com/ios-사진으로-보는-aspectfit-aspectfit-scaletofill-f41470d0191f)

🐛 ArtisTappedView(= 작가디테일뷰) 네비게이션바 관련 버그 수정

---

Flicker/Screens/Main/MainViewController.swift

메인화면에서 스크롤 시에, 데이터가 불규칙하게 불러오는 경향이 있었습니다.
데이터를 불러오는 동안, 화면을 그리는 작업과 데이터베이스를 추가적으로 불러오는 것을 겹치지 않게 하기 위해, Bool 변수를 추가하였습니다.
- dataMayContinue 변수를 추가해서, 불규칙한 무한스크롤 에러를 해결하였습니다.
https://user-images.githubusercontent.com/57849386/204096654-4b3d7a6d-29dd-47bf-aa03-98d27cf29206.mp4
- closed #145
https://stackoverflow.com/questions/47220268/firebase-firestore-pagination-with-swift

🐛 메인화면 무한 스크롤 에러 해결

---

Flicker/Global/Supports/SceneDelegate.swift
Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/Profile/ProfileHeaderVIew.swift
Flicker/Screens/Profile/ProfileViewController.swift

이메일이 길어지면 표시하기 애매하다는 점과 글자수를 제한하여 맞는 방면으로 표기하기 위함입니다.
- Email Label을 제거하고 위치를 조절했습니다.
- 최대 8글자가 들어가기에는 현재 LargeTitle이 너무 크기 때문에 Title1로 스타일을 선정했습니다.
- 간단한 수정이라 스크린샷만 보셔도 됩니다.
close #129

💄 헤더뷰 안의 이메일을 삭제하고 아이디의 설정을 바꿨습니다. + 헤더뷰 위치 재조정되는 버그를 수정했습니다.

---

Flicker/Screens/Profile/Cell/ProfileEnumeration.swift
Flicker/Screens/Profile/ProfileViewController.swift

푸시 알람 관련하여, 앱의 알림 설정을 온오프 할 수 있는 기능을 추가하였습니다.
토글 버튼으로 있던 "알람 온오프" 항목을 "알림설정"버튼으로 수정하고, 클릭시에 앱 설정화면으로 넘어가게하였습니다.
놀랍게도 앱설정으로 가는 것은 가능한데, 설정화면의 세부화면으로 가는 것은 불가능하다고 합니다. 맨 하단에 참고링크 읽어보세요!
</p>
https://user-images.githubusercontent.com/57849386/204306876-ac13f66c-b3d8-4729-98cd-1cdd649eea47.mp4
- closed #153
https://velog.io/@haze5959/iOS-%EC%84%A4%EC%A0%95%EC%95%B1%EC%9D%98-%ED%8A%B9%EC%A0%95-%ED%99%94%EB%A9%B4%EC%9C%BC%EB%A1%9C-%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B0

✨ 프로필뷰 알림 설정 버튼 활성화

---

Flicker/Screens/SignUp/LoginProfileViewController.swift
Flicker/Screens/SignUp/SignUpViewController.swift

- 프로필 세팅뷰에서 일정 길이 이상으로 닉네임의 String값이 들어가면 UI적으로 문제가 생겨 자체적으로 닉네임의 길이를 8글자로 제한하기로 했습니다.
- 닉네임을 적는 텍스트 필드의 길이가 8글자 이상이 될 경우 더 이상 입력을 할 수 없도록 했습니다.
- 추가적으로 모든 입력이 불가해, 지우기 조차 불가하여 백스페이스입력은 가능하도록 코드를 추가했습니다.
- UI적으로 현재 몇글자를 입력했고 몇글자까지 입력할 수 있는지 보여줘 사용자가 알 수 있도록 했습니다.
String은 호출되는 함수의 Parameter로 들어오는 값이며, 사용자가 입력을 시도한 값이 실제 입력이 되는지 여부와 관계없이 계속 들어오게 됩니다. 이때 들어오는 값중 BackSpace값을 판단하고 인코딩하여 UInt32형태로 변환합니다.
BackSpace의 UInt32값은 -92이며,이 조건을 만족하는 경우는 입력을 가능하도록 하여 BackSpace입력은 가능하도록 했습니다.
https://user-images.githubusercontent.com/81131715/204367485-bbfaebe4-e251-4f66-a297-bd6796199af6.mp4
회원가입 시 프로필입력 화면에서 닉네임을 입력해보시면 됩니다!
- closed #160 
- https://kasroid.github.io/posts/ios/20200914-uitextfield-limits-number-of-text-detecting-backspace-event/#backspac …

✨ 회원가입시 닉네임의 길이를 8글자로 제한하는 기능을 추가했습니다.

---

Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/Main/MainViewController.swift
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/Tabbar/TabbarViewController.swift

- 네비게이션바 문제로 생각되었던 프로필세팅 뷰의 헤더가 올라가던 부분이 네비게이션 바 문제가 아닌 테이블 뷰내에서 테이블 뷰 헤더를 한번 더 선언하여 헤더의 크기만큼 테이블 뷰의 공간이 헤더위치에 생겨 올라가던 것이였습니다.
- 테이블 뷰 헤더의 오토레이아웃을 뷰자체에 맞추고 테이블뷰도 따로 맞췄습니다.
https://user-images.githubusercontent.com/81131715/204422130-06c3c18a-7d0e-4323-9633-acd3496b80a5.mp4
- 화면을 왓다리갔다리 해보시면 됩니다.
- closed #162

💄 프로필 세팅 뷰에 있던 프로필 테이블뷰의 헤더가 올라가던 버그를 해결했습니다.

---

Flicker.xcodeproj/project.pbxproj
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift
Flicker/Screens/Tabbar/TabbarViewController.swift

- 프로필 수정과 연관되어 버그가 존재했습니다. 
- 이미지를 변경할시 기존 닉네임을 그대로 살려서 수정 가능하게 했습니다. 사용자가 자신의 정보를 변경하고자 할경우 정상 반영됩니다.
- 빈문자열이 안 들어가게 조치했습니다.
- 수정완료 버튼을 누르면 바로 이전뷰로 돌아가게 조치했습니다.
- ProfileView와 ProfileSettingView 쪽을 보시면 되겠습니다!
close #157

🐛 ProfileSetting에서 이동이 가능하게 만들었고 버튼을 눌렀을때 돌아가는 곳을 Profile로 수정했습니다.

---

Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
Flicker/Screens/Main/MainViewController.swift

디바이스에 따라, 작가 썸네일 셀의 비율이 다르게 보이는 에러를 수정했습니다.
- 300으로 고정이었던 셀의 높이를, 피그마를 참고하여, 너비의 0.85의 배율로 수정했습니다.
</p>
</p>
- closed #167

🎨 메인화면 작가 썸네일 셀 비율 수정

---

Flicker/Screens/Main/MainViewController.swift

작가디테일뷰를 들어가면 네비게이션바가 없어지는 현상이 발생했습니다.
메인뷰에서 작가셀을 탭하여 네비게이션될때, 숨겼던 네비게이션바를 다시 숨김해제하는 코드가 없습니다. 메인뷰컨의 버그를 수정하는 과정에서 삭제된 것으로 예상되네요
setNavigationBarHidden(fasle) 코드를 추가해서 해결했습니다.
</p>
#168

:bug: ArtistTappedView의 네비게이션바 관련 버그 수정

---

Flicker.xcodeproj/project.pbxproj
Flicker/Global/Utils/Static.swift
Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
Flicker/Screens/Profile/ProfileHeaderVIew.swift
Flicker/Screens/Profile/ProfileViewController.swift
Flicker/Screens/SignUp/LoginProfileViewController.swift
Flicker/Screens/SignUp/SignUpViewController.swift
Flicker/Screens/WithDraw/WithDrawViewController.swift

- 피파의 디자인 수정 및 맡은 뷰에 한해서 각 기기별 대응을 할 수 있도록 코드를 수정했습니다.
- StaticValue로 디바이스의 높이와 너비를 추가했습니다.
- 그래서 각 고정값으로 되어있던 높이 와 너비 값들을 기기별로 비례해서 구현되도록 변경하였습니다.
- 동영상 두개는 기기별 호환여부를 중점으로 보시면 되며, 하단의 GIF는 디자인을 보시면 됩니다.
- 아이폰 SE3세대
https://user-images.githubusercontent.com/81131715/204472690-f8039f4d-e0d9-4626-91f1-1c4f249fab6c.mp4
- 아이폰 14proMAX
https://user-images.githubusercontent.com/81131715/204472679-8e3d4658-abef-4f12-94ad-61b672b65567.mp4
- 마지막 커밋 수정본
- 현재 작성 중인 Pull Request와 관련된 PR과 Issues가 있다면 나열합니다.
- closed #170

💄 기기의 너비,높이 값 Static으로 추가 & 기기별 대응하도록 UI수정

---

Flicker.xcodeproj/project.pbxproj
Flicker/Global/Supports/SceneDelegate.swift
Flicker/Global/Utils/FirebaseManager.swift
Flicker/Models/EditData.swift
Flicker/Models/User.swift
Flicker/Screens/ArtistEdit/Cell/ArtistEditItemsTableViewCell.swift
Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditDescriptionViewController.swift
Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditGearsViewController.swift
Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditPortfoiloViewController.swift
Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditRegionsViewController.swift
Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditTagsViewController.swift
Flicker/Screens/ArtistEdit/ViewControllers/ArtistEditViewController.swift
Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
Flicker/Screens/ArtistRegister/ViewControllers/RegisterConceptTagViewController.swift
Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
Flicker/Screens/Profile/Cell/ProfileEnumeration.swift
Flicker/Screens/Profile/ProfileViewController.swift

- 작가 정보 중 포트폴리오 수정 뷰를 따로 뺀건, 생각보다 볼륨이 크기 때문이었습니다.
- 네트워크 관련된 함수와 모델을 따로 구현해야 했으며, 오류가 생기면 유저의 UX를 크게 저해하기 때문에 꼼꼼한 설계가 필요했습니다.
- Artist 모델을 바로 사용하지 않고, edit 에 필요한 부분을 따로 모델로 만들었습니다.
- firebase 에서 데이터를 주고 받는 함수들을 만들었습니다.
- edit 하면, storage 에 올라가 있는 사진은 모두 삭제되며, 새롭게 만들어진 포트폴리오가 업로드 됩니다.
- 이미지를 수정하지 않았을 때의 상황도 분기처리를 해서 문제가 없습니다.
- 로딩뷰도 당연히 만들었습니다.
- 새로 만든 모든 뷰에 이해를 돕기 위한 주석을 처리했습니다. 유지보수에 용이해질 것이라 생각합니다.
https://user-images.githubusercontent.com/89404664/204521262-f17c2999-85bf-4035-ab21-4f41754078e7.mp4
작가가 등록 후, 프로필에서 작가 수정을 누르면 됩니다.
- Closed #102 
- Closed #164

✨ 작가의 정보 중 포트폴리오(이미지) 를 수정할 수 있습니다.

---

Flicker/Screens/Tabbar/TabbarViewController.swift

🚨 탭바에서 검색뷰를 임시 삭제합니다

---

Flicker/Global/Base/BaseViewController.swift
Flicker/Screens/SignUp/LoginProfileViewController.swift
Flicker/Screens/SignUp/SignUpViewController.swift

- 앱에 대한 버그를 찾으며 UX에 증가를 위한 과정 중 나온 회원가입 뷰의 추가 기능 입니다.
- backButton의 경우 통일성을 위해서 피칸파이의 코드를 선언하여 사용했습니다.
- 스와이프 제스쳐의 경우 baseVC에 이미 버그에 대한 부분까지 코드가 잘 짜여져있는 것을 발견하여, 추가했습니다.
사용을 원하는 뷰에서는 선언만 해주면 바로 영상과 같이 사용이 가능합니다.
https://user-images.githubusercontent.com/81131715/204825390-79d9282f-255b-42ff-9f60-7dd52507fdbb.mp4
- 제스쳐 기능 확인 및 뒤로가기 기능을 확인해주시면 됩니다.
- 현재 작성 중인 Pull Request와 관련된 PR과 Issues가 있다면 나열합니다.
- closed #185

💄  회원가입 플로우에 뒤로가기 버튼 추가 및 스와이프 제스쳐 기능 추가

---

Flicker/Screens/Login/ResetPassword/PopUpViewController.swift

- 앱 최종 확인시 발견된 UI적 버그
- 폰트 크기 수정
- 팝업 뷰의 topAnchor수정하여 키보드보다 위로 보여지도록 했습니다.
</p>
- closed #190

💄 PopUpViewcontroller의 UI를 수정사항에 맞게 수정하여 반영하였습니다.

---

Flicker/Global/Utils/FirebaseManager.swift
Flicker/Models/User.swift
Flicker/Screens/Login/LoginViewController.swift
Flicker/Screens/ProfileSetting/ProfileSettingViewController.swift
Flicker/Screens/SignUp/LoginProfileViewController.swift

- 작가등록 후 로그아웃시 발생되는 치명적인 버그를 발견했습니다.
- 서버 및 UserDefaults에 isArtist값을 저장합니다.
</p>

🐛  작가등록 후 로그아웃시 작가등록 여부 값을 저장하는 코드를 추가했습니다.

---

Flicker/Screens/Region/RegionViewController.swift
Flicker/Screens/Region/UIComponent/RegionTagListView.swift

- 지역 태그를 10개 이상 선택하면, 앱이 터지는 에러를 수정했습니다.
- 파이어베이스 쿼리에서 10개이상을 조회하는 것을 지원하지 않습니다. 따라서 지역 태그 선택을 10개이상 했을 시에, 첫번째선택된 태그를 해제하도록 하였습니다.
https://user-images.githubusercontent.com/57849386/206328627-60e4b61a-f2c2-4e84-9c4e-d88abc7d7ab7.mp4
- 태그를 마구마구 눌러보세요,
- closed #195

🐛 지역 태그 10개 넘을시, 처음꺼 삭제

---

Flicker/Screens/Chat/ChatViewController.swift

- 채팅시에, 전송 버튼을 누를 때 키보드가 닫혀서 채팅이 불편하던 UX를 개선하였습니다.
- 터치 시에, 키보드가 사라지는 뷰의 범위를 수정하였습니다.
- 디바이스에 설치 후, 채팅기능을 사용해보시면, 개선된 UX를 체감할 수 있습니다.
- closed #196

🐛 채팅시에 키보드 Hide 범위 수정

---

Flicker/Screens/Artist/ArtistTappedViewController.swift
Flicker/Screens/Artist/ImageSliderViewController.swift
Flicker/Screens/Main/MainViewController.swift

1. 전체화면 취소 버튼이 백버튼 모양에서 x 표시로 변경되었습니다.
2. 작가디테일뷰에서 왼쪽 스와이프해서 뒤로가기 기능이 추가되었습니다.

💄 작가 포트폴리오 이미지 전체화면 취소 버튼 UI 변경 및 작가디테일뷰 스와이프해서 뒤로가기 추가

---

Flicker/Screens/SignUp/LoginProfileViewController.swift

- 지인에게 앱 소개를 하며 앱을 확인하는 도중 회원가입시 화면이 넘어가지 않는 치명적인 기능적 이슈를 발견했습니다.
- 전에 버그로 나왔었던 지우기 버튼이 화면을 클릭하면 사라지는 문제를 해결하였습니다.
- 작가등록 여부에 대한 UI를 지우면서 이와 관련된 로직을 전부 제거하였습니다.

:bug: 회원가입 시 발생되는 버그 해결
